import OpenAI from "openai";
import { NextResponse } from "next/server";
import { cleanArray,cleanNumber,cleanText,guardAIRequest } from "@/lib/serverGuard";

const schema={type:"object",properties:{difficulty:{type:"string",enum:["recover","steady","stretch"]},prerequisiteNote:{type:"string"},trial1:{type:"object",properties:{title:{type:"string"},proof:{type:"string"},xp:{type:"integer"}},required:["title","proof","xp"],additionalProperties:false},trial2:{type:"object",properties:{title:{type:"string"},proof:{type:"string"},xp:{type:"integer"}},required:["title","proof","xp"],additionalProperties:false},boss:{type:"object",properties:{title:{type:"string"},proof:{type:"string"},xp:{type:"integer"}},required:["title","proof","xp"],additionalProperties:false},reason:{type:"string"}},required:["difficulty","prerequisiteNote","trial1","trial2","boss","reason"],additionalProperties:false};

export async function POST(req:Request){
  const blocked=guardAIRequest(req,"weekly");if(blocked)return blocked;
  try{
    if(!process.env.OPENAI_API_KEY)return NextResponse.json({error:"Weekly adaptation is temporarily unavailable."},{status:503});
    const body=await req.json();const path={name:cleanText(body.path?.name,180),capability:cleanText(body.path?.capability,500)};const currentNode=cleanText(body.currentNode,220);const nextNode=cleanText(body.nextNode,220);const weekNumber=cleanNumber(body.weekNumber,1,999,1);const progress=cleanNumber(body.progress,0,100,0);const capacity=cleanText(body.capacity,30)||"steady";const previousWeek=cleanArray<any>(body.previousWeek,8);const recentProofs=cleanArray<any>(body.recentProofs,6);const archive=body.archive?{easier:cleanText(body.archive.easier,700),resisted:cleanText(body.archive.resisted,700),next:cleanText(body.archive.next,700)}:null;const firstWeek=weekNumber===1;
    if(!path.name||!currentNode)return NextResponse.json({error:"This Path needs more structure before its Week can adapt."},{status:400});
    const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
    const response=await client.responses.create({model:process.env.OPENAI_MODEL||"gpt-5-mini",input:[{role:"system",content:"You are BECOMR's adaptive weekly progression architect. Build real-world capability challenges that a person can actually perform this week. Never write template filler. Every mission must specify what the user does, an appropriate quantity/duration/output, and what evidence proves completion. Use domain-appropriate Proof. Use prior Proof and reflection when available. If foundations are missing, narrow the challenge and clearly name the prerequisite."},{role:"user",content:`Path: ${path.name}\nCapability: ${path.capability}\nCurrent node: ${currentNode}\nNext node: ${nextNode}\nWeek: ${weekNumber}\nPath progress: ${progress}%\nCapacity: ${capacity}\nThis is the first Week: ${firstWeek}\nPrevious weekly results: ${JSON.stringify(previousWeek).slice(0,7000)}\nRecent Proof: ${JSON.stringify(recentProofs).slice(0,5000)}\nLatest Archive reflection: ${JSON.stringify(archive)}\n\nGenerate two ordered Weekly Trials and one Boss. ${firstWeek?"Trial I must establish a useful baseline and Trial II must build on it.":"Trial I should respond to current performance and Trial II should bridge toward the next node."} The Boss must combine both Trials into one meaningful real-world result. Give concrete thresholds whenever the domain allows it.`}],text:{format:{type:"json_schema",name:"becomr_weekly_adaptation",strict:true,schema}}});
    const output=response.output_text?.trim();if(!output)return NextResponse.json({error:"Your current Weekly missions remain active while BECOMR realigns them."},{status:502});
    try{return NextResponse.json(JSON.parse(output))}catch{return NextResponse.json({error:"Your current Weekly missions remain active while BECOMR realigns them."},{status:502})}
  }catch(error:any){const status=Number(error?.status)||500;const message=status===429?"BECOMR is aligning many Weeks right now. Your current missions remain available.":"Your current Weekly missions remain available.";return NextResponse.json({error:message},{status:status>=400&&status<600?status:500})}
}
