import OpenAI from "openai";
import { NextResponse } from "next/server";
import { cleanArray,cleanNumber,cleanText,guardAIRequest } from "@/lib/serverGuard";

const schema={type:"object",properties:{title:{type:"string"},proof:{type:"string"},xp:{type:"integer"},reason:{type:"string"},difficulty:{type:"string",enum:["recover","steady","stretch"]},prerequisiteNote:{type:"string"}},required:["title","proof","xp","reason","difficulty","prerequisiteNote"],additionalProperties:false};

export async function POST(req:Request){
  const blocked=guardAIRequest(req,"next-trial");if(blocked)return blocked;
  try{
    if(!process.env.OPENAI_API_KEY)return NextResponse.json({error:"Adaptive alignment is temporarily unavailable."},{status:503});
    const body=await req.json();const path={name:cleanText(body.path?.name,180),capability:cleanText(body.path?.capability,500)};const currentNode=cleanText(body.currentNode,220);const recentProofs=cleanArray<any>(body.recentProofs,6).map(p=>({title:cleanText(p?.title,220),evidence:cleanText(p?.evidence,800)}));const archive=body.archive?{easier:cleanText(body.archive.easier,700),resisted:cleanText(body.archive.resisted,700),next:cleanText(body.archive.next,700)}:null;const weekNumber=cleanNumber(body.weekNumber,1,999,1);const progress=cleanNumber(body.progress,0,100,0);const capacity=cleanText(body.capacity,30)||"steady";
    if(!path.name||!currentNode)return NextResponse.json({error:"This Path needs a current capability before BECOMR can adapt it."},{status:400});
    const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
    const response=await client.responses.create({model:process.env.OPENAI_MODEL||"gpt-5-mini",input:[{role:"system",content:"You are BECOMR's adaptive progression engine. Generate the single best next real-world Trial based on demonstrated capability. Never repeat the same accomplishment. Use recover when evidence shows repeated struggle or limited capacity, steady for normal progress, and stretch only when recent evidence shows strong success. If a foundation is missing, create a prerequisite-strengthening Trial and name it in prerequisiteNote. Every Trial must have measurable or reviewable Proof. Never create vague tasks like study, learn, research, practice more, or improve."},{role:"user",content:`PATH: ${path.name}\nCAPABILITY: ${path.capability||path.name}\nCURRENT NODE: ${currentNode}\nPATH PROGRESS: ${progress}%\nPATH WEEK: ${weekNumber}\nCAPACITY: ${capacity}\n\nRECENT PROOF:\n${recentProofs.length?recentProofs.map((p:any,i:number)=>`${i+1}. ${p.title} — ${p.evidence||"completed"}`).join("\n"):"No prior Proof supplied."}\n\nLATEST REFLECTION:\nEasier: ${archive?.easier||"none"}\nResisted: ${archive?.resisted||"none"}\nNext bearing: ${archive?.next||"none"}\n\nCreate ONE next Daily Trial. It must be meaningfully different from recent Proof, achievable now, measurable, and aligned with demonstrated ability. XP 30-100.`}],text:{format:{type:"json_schema",name:"becomr_next_trial",strict:true,schema}}});
    const output=response.output_text?.trim();if(!output)return NextResponse.json({error:"BECOMR kept the current Trial because a tailored replacement was not ready."},{status:502});
    try{return NextResponse.json(JSON.parse(output))}catch{return NextResponse.json({error:"BECOMR kept the current Trial because adaptation was incomplete."},{status:502})}
  }catch(error:any){const status=Number(error?.status)||500;const message=status===429?"BECOMR is aligning many challenges right now. Your current Trial remains available.":"BECOMR kept your current Trial and will adapt again later.";return NextResponse.json({error:message},{status:status>=400&&status<600?status:500})}
}
